### ISSUE TITLE
Form Component Templates?

### ISSUE THREAD

**Issue by StephenOTT** [formio/ngFormBuilder#128]
Any thoughts on support for Component templates?  Ability to configure a component in a  form and then save that configuration for quick use later on?

Also a variation on this would be support to allow you to use the template in multiple forms and only have to make the change in 1 location to have all forms updated with the change to the template vs when you use the template it just does a one time copy of the config into the form.

**Comment by zackurben** [comment]
@StephenOTT This is already available for Resources (called "Existing Resource Fields" in the form builder.)

Currently, it is a shallow copy, so a change to one copied field, will not be reflected in the others.
