### ISSUE TITLE
Wizard page nav bug?

### ISSUE THREAD

**Issue by StephenOTT** [formio/ngFormBuilder#131]
Changing pages in the wizard builder seems to have some bugs?  Looking for confirmation.

Able to replicate in Safari and Chrome.

The UI seems to get stuck when trying to nav between pages in the builder.  You select Page 1 vs Page 2 and the colours change, but the form builder does not.  Pages seem to also get out of order.  

This known?

If unable to replicate or see the same issue, will update with further gifs and specific replication steps.

**Comment by zackurben** [comment]
I can't reproduce this, if you still have an issue, feel free to reopen this.
