### ISSUE TITLE
Error loading the builder

### ISSUE THREAD

**Issue by priand** [formio/ngFormBuilder#163]
I'm experimenting formio and I created a test app that works perfectly with https://npmcdn.com/ng-formio-builder@1.12.13/dist/ngFormBuilder-complete.js (from the code pen). Now, when try with the files in the dist/ repo instead, I'm getting this error:
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module formioApp due to:
Error: [$injector:modulerr] Failed to instantiate module ngFormBuilder due to:
ReferenceError: _ is not defined
```
It comes from the email component:
```
module.exports = function(app) {
  app.config([
    'formioComponentsProvider',
    function(formioComponentsProvider) {
      var views = _.cloneDeep(formioComponentsProvider.$get().components.textfield.views);
```
Where it looks like '_' is not available (lodash not yet loaded?)

**Comment by travist** [comment]
This is probably because we are not exposing the _ as a global like we had to do with SignaturePad on the renderer....

https://github.com/formio/ngFormio/blob/master/gulp/scripts-full.js#L8

We will take a look soon, but until then you may try to create a new build if you can and change the gulp scripts to define the "_" globally like we do here by saying

```
,
      insertGlobalVars: {
        "_": function() {
          return 'require("lodash")';
        }
      }
```

**Comment by priand** [comment]
Thanks! I added this option to the browserify options and it did the trick. I'll let you close the bug after you deliver your solution.

**Comment by priand** [comment]
Actually this is strange. I thought it works, but now I have a browserify problem where it says that it cannot find module lodash in src/components. It appeared today after I added a new component, I don't know why...
I worked around it by removing the insertGlobalVars (which removes the issues), and made lodash the first requirement in ngFormBuilder-full,js, while storing its result in _
`window._ = require('lodash');`
Looks like a hack, but it works

**Comment by travist** [comment]
This is what I ended up doing in the latest version. Check out the latest and you will get the change. Thanks.
