### ISSUE TITLE
index.html is not up-to-date

### ISSUE THREAD

**Issue by priand** [formio/ngFormBuilder#164]
The script/css references in index.html point to cdn served files, but trying to run the file in a local browser lead to an error:
```
formio-full.min.js:48 Uncaught Error: [$injector:modulerr] Failed to instantiate module formBuilder due to:
Error: [$injector:modulerr] Failed to instantiate module ngFormBuilder due to:
Error: [$injector:modulerr] Failed to instantiate module dndLists due to:
Error: [$injector:nomod] Module 'dndLists' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.8/$injector/nomod?p0=dndLists
```
Think it should anyway be better to have the references pointing to ./dist instead, which could help validating a build.
Also, it includes to css/formBuilder.css that is not misspelled (should be ngFormBuilder.css?)

**Comment by travist** [comment]
This is now representative of our index.html file. http://formio.github.io/ngFormBuilder/  It seems it works. Please let us know if you are seeing something different.
