### ISSUE TITLE
Page wizard - unexpected behaviour when dropping components outside page container

### ISSUE THREAD

**Issue by laradevitt** [formio/ngFormBuilder#168]
Unfortunately I can't seem to use the Wizard with much success, and this seems largely (if not entirely) related to the fact that it's very easy to drop form elements outside of the parent _.form-group_ container (the one with the _Page_ header). The usual result is that form elements that were previously added disappear, or that the containers get swapped ('Page 1' appears when clicking on in 'Page 2').

I can get things to work reasonably well if I'm extra careful, but _not_ dropping elements outside the container is actually quite hard to do, and one small slip can result in lost work. 

The behaviour is the same on both the CodePen demo, which uses v. 1.12.13 and an implementation on my local machine, which uses 2.2.4 (via CDN). 

It's pretty easy to replicate. 

1. Toggle to 'Wizard' mode
2. Click '+ page' button
3. Click 'Page 2'
4. Drag-and-drop a text field into the area _inside_ the container; hit 'Save' to close modal.
5. Click 'Page 1', then back to 'Page 2' - everything is good, field is there.
6. Drag-and-drop a text field into the area _outside_ the container; hit 'Save' to close modal.
7. Click 'Page 1', then back to 'Page 2' - area is empty.

Chrome 53.0.2

Not sure if this is something I can fix myself, but I will look at it. In the meantime let me know if you need any more info. Thanks a lot -

_Edit: updated issue title_

**Comment by travist** [comment]
Yeah, I am able to reproduce.  I think the solution here is to force the drops outside to move the object inside of the panel object (append if they drop below, and prepend if they drop above). I actually don't think it would be to hard to get this to work. Let me try a few things.

**Comment by travist** [comment]
This should be the fix for this problem. We are doing some testing on our end, but have done a few tests and it works. https://github.com/formio/ngFormBuilder/pull/169

**Comment by travist** [comment]
This has been pulled in and should be fixed with latest version. 

http://formio.github.io/ngFormBuilder/

**Comment by laradevitt** [comment]
Works well for me. Thanks for the quick fix!
