### ISSUE TITLE
$scope is overlapped by formIO default form components.

### ISSUE THREAD

**Issue by KBasher** [formio/ngFormBuilder#170]
In form edit mode in form builder, I am trying to assign my saved form components json object in the $scope. But it is not binding in form builder, it is binding a default submit button always.

My form building code is 

```
angular.module('formioApp', [
          'ui.bootstrap',
          'ui.select',
          'formio',
          'ngFormBuilder',
          'ngJsonExplorer'
    ]).controller('formioAppCtrl', function ($scope) {
        $scope.form = {
            components: [],
            display: 'form'
        };
        $scope.$on('formSubmission', function (err, submission) {
            console.log("Saved");
            console.log(submission);
        })

        $scope.submission = {
            data: {
                //"firstName": "Khademul"
            }
        };
    });
```

In javascript I am trying to assign my saved form components object

```
angular.element("form:first").scope().form.components = formSchemaJSON;
var $scope = angular.element("form:first").scope();
$scope.$apply();
```

I think the scope is overlapped by form IO default components.

How to fixed it?

Is there a way to disable the scope change by form IO?

**Comment by KBasher** [comment]
Hi, I have fixed the binding issue. Now in edit mode the form element is binding. 
But every time it is adding a extra Submit button. 

How can I stop adding the Submit button with my form?

**Comment by randallknutson** [comment]
I've added a pull request to fix this issue for you. You can use the bugfix/submit-append branch or we should have this merged in shortly.

**Comment by KBasher** [comment]
Hi Randallknutson,
I have downloaded this file from link https://github.com/formio/ngFormBuilder/blob/1707a42e9b427cb77c8bacfa04437f7ef4616fc2/dist/ngFormBuilder-complete.js  in which you have made changes I think and have replaced my previously used formbuilder js file <script src="http://npmcdn.com/ng-formio-builder@1.12.13/dist/ngFormBuilder-complete.js" type="text/javascript"></script>.

But your changed js file still adding a submit button and a new problem is showing, my form component binding is not working.

I have tested replacing the old js file and new js file but yours one is not working.

**Comment by laradevitt** [comment]
@KBasher - If it helps, this is the code change introduced in #171 above:

https://github.com/formio/ngFormBuilder/commit/94b0c31d869248b5e542cab2ca69b163648a4002#diff-d01c1a9377f9d59c6753be3220a04563

**Comment by Robmacker** [comment]
@laradevitt - my friend @KBasher and I thank you for that!

**Comment by KBasher** [comment]
I have downloaded the file dist/ngFormBuilder-complete.js and added in place of http://npmcdn.com/ng-formio-builder@1.12.13/dist/ngFormBuilder-complete.js. Using the new one my form binding in edit mode is not working and extra submit button is adding still.

**Comment by KBasher** [comment]
Hi, I have download the js code from  http://npmcdn.com/ng-formio-builder@1.12.13/dist/ngFormBuilder-complete.js and made changes in three places and it work for me both form binding in edit mode and extra submit button is not adding.

original code
`if (!$scope.form || !$scope.form.components || !$scope.form.components.length) {
          $scope.form = {components:[submitButton]};
        }
        else {
          $scope.form.components.push(submitButton);
        }`
changed code

`if (!$scope.form || !$scope.form.components || !$scope.form.components.length) {
          $scope.form = {components:[]};
        }
        else {
          //$scope.form.components.push(submitButton);
        }`

and I comment that line

`if ($scope.formio && $scope.formio.formId) {
          $scope.formio.loadForm().then(function(form) {
            $scope.form = form;
            $scope.form.page = 0;
            if ($scope.form.components.length === 0) {
              //$scope.form.components.push(submitButton);
            }
          });
        }`

**Comment by randallknutson** [comment]
I've added a new pull request in #173 that will give an option to not add submit buttons. Use it like this:

<form-builder options="{noSubmit: true}"/>

**Comment by KBasher** [comment]
The problem is fixed. Thanks.
