### ISSUE TITLE
File Upload is not working.

### ISSUE THREAD

**Issue by KBasher** [formio/ngFormBuilder#176]
I am unable to upload a file with the other form data. The form data is uploading but the uploaded file is missing.
I am following the guideline given at https://github.com/danialfarid/ng-file-upload#server-side 
I have used this sample code
`div class="button" ngf-select="upload($file)">Upload on file select/div
div class="button" ngf-select="uploadFiles($files)" multiple="multiple"Upload on file select/div
  Drop File:
div ngf-drop="uploadFiles($files)" class="drop-box"
  ngf-drag-over-class="'dragover'" ngf-multiple="true" 
  ngf-pattern="'image/*,application/pdf'"Drop Images or PDFs files here/div
div ngf-no-file-drop>File Drag/Drop is not supported for this browser/div`

But this sample code is not working.

**Comment by KBasher** [comment]
Hi, I am able to upload an image following the guideline given at https://github.com/danialfarid/ng-file-upload#server-side  in a test page.
But Form Builder File Upload is not working. I have added a url in setup option for File Upload and when I browse a file in View that time it shows a error "File Upload URL not provided". Does file is not uploading because of this error? The setup option and error images are follows.
[
![fileurlset](https://cloud.githubusercontent.com/assets/10288418/19686693/2940f2f0-9ae4-11e6-9aa5-a10c703f0c1a.jpg)
](url)

[
![view](https://cloud.githubusercontent.com/assets/10288418/19686710/3882237e-9ae4-11e6-84e5-5ff8d5fe10a7.jpg)
](url)

**Comment by manind0078** [comment]
Hi, I am also facing same issues, Can u please share the working document?
