### ISSUE TITLE
Code to convert Display option from Form to Wizard in Form Builder.

### ISSUE THREAD

**Issue by KBasher** [formio/ngFormBuilder#184]
Hi, I am binding the form builder using display option to form. I have put a drop down with option Form and Wizard.

Now when I change the dropdown value from form to wizard, how can I change the form builder view from form to Wizard?

Please give me the sample angular code.

**Comment by travist** [comment]
This codepen does exactly that. Source code provided.

http://codepen.io/travist/full/xVyMjo/
