### ISSUE TITLE
Wizard binding is not working.

### ISSUE THREAD

**Issue by KBasher** [formio/ngFormBuilder#187]
Hi, I am facing a problem when working with wizard.
I am giving the form builder a wizard json but it is not displaying perfect.

I have created a wizard like below.

![originaljson](https://cloud.githubusercontent.com/assets/10288418/20140935/2510b668-a6b8-11e6-81aa-9bb6dc3969c9.png)

But when I am binding this json to regenerate the wizard it is not displaying perfectly.

The Json I have set shown below
`angular.module('formioApp', [

              'ui.bootstrap',
              'ui.select',
              'formio',
              'ngFormBuilder',
              'ngJsonExplorer'
	    ]).run([
              '$rootScope',
              'formioComponents',
              '$timeout',
              function ($rootScope, formioComponents, $timeout) {
                  $rootScope.displays = [
                      {
                          name: 'form',
                          title: 'Form'
                      },
                      {
                          name: 'wizard',
                          title: 'Wizard'
                      }
                  ];
                  $rootScope.form = {
                      "components": [
                        {
                            "type": "panel",
                            "input": false,
                            "title": "Page 1",
                            "theme": "default",
                            "components": [
                              {
                                  "input": true,
                                  "tableView": true,
                                  "inputType": "text",
                                  "inputMask": "",
                                  "label": "Name",
                                  "key": "name",
                                  "placeholder": "",
                                  "prefix": "",
                                  "suffix": "",
                                  "multiple": false,
                                  "defaultValue": "",
                                  "protected": false,
                                  "unique": false,
                                  "persistent": true,
                                  "validate": {
                                      "required": false,
                                      "minLength": "",
                                      "maxLength": "",
                                      "pattern": "",
                                      "custom": "",
                                      "customPrivate": false
                                  },
                                  "conditional": {
                                      "show": "",
                                      "when": null,
                                      "eq": ""
                                  },
                                  "type": "textfield",
                                  "$$hashKey": "object:179",
                                  "tags": []
                              }
                            ],
                            "$$hashKey": "object:143"
                        },
                        {
                            "type": "panel",
                            "title": "Page 2",
                            "isNew": true,
                            "components": [
                              {
                                  "input": true,
                                  "tableView": true,
                                  "inputType": "text",
                                  "inputMask": "",
                                  "label": "Address",
                                  "key": "address",
                                  "placeholder": "",
                                  "prefix": "",
                                  "suffix": "",
                                  "multiple": false,
                                  "defaultValue": "",
                                  "protected": false,
                                  "unique": false,
                                  "persistent": true,
                                  "validate": {
                                      "required": false,
                                      "minLength": "",
                                      "maxLength": "",
                                      "pattern": "",
                                      "custom": "",
                                      "customPrivate": false
                                  },
                                  "conditional": {
                                      "show": "",
                                      "when": null,
                                      "eq": ""
                                  },
                                  "type": "textfield",
                                  "$$hashKey": "object:311",
                                  "tags": []
                              }
                            ],
                            "input": false,
                            "key": "page2",
                            "$$hashKey": "object:293",
                            "theme": "default"
                        }
                      ],
                      "display": "wizard",
                      "page": 1,
                      "numPages": 2
                  };
                  var originalComps = _.cloneDeep($rootScope.form.components);
                  //originalComps.push(angular.copy(formioComponents.components.button.settings));
                  $rootScope.jsonCollapsed = true;
                  $timeout(function () {
                      $rootScope.jsonCollapsed = false;
                  }, 200);
                  var currentDisplay = 'form';
                  $rootScope.$watch('form.display', function (display) {
                      if (display && display !== currentDisplay) {
                          currentDisplay = display;
                          if (display === 'form') {
                              $rootScope.form.components = originalComps;
                          } else {
                              $rootScope.form.components = [{
                                  type: 'panel',
                                  input: false,
                                  title: 'Page 1',
                                  theme: 'default',
                                  components: originalComps
                              }];
                          }
                      }
                  });
              }
	    ]);`
The generated wizard is below

![screen](https://cloud.githubusercontent.com/assets/10288418/20141003/87fc370c-a6b8-11e6-89e7-0fb83f26eac1.png)

I found the json is displaying in the right side after regenerate, some property has changed automatically to 

`page: 0,
numPages: 1`

**Comment by anupriya7295** [comment]
In wizard mode entire json is displayed within panel  therefore Wizard pages wrap inside single panel 
$rootScope.form.components = [{
                type: 'panel',
                input: false,
                title: 'Page 1',
                theme: 'default',
                components: originalComps
              }];
where originalComps is our json  it is wrapped inside panel replace this code with 
$rootScope.form.components = originalComps;
here we are assigning our json format it will display form correctly
