### ISSUE TITLE
Date / Time Component

### ISSUE THREAD

**Issue by VelChen** [formio/ngFormBuilder#188]
in "Date/Time Component" →
date →
Initial Mode
it works incorrectly.

in datetime.js. line num 96
change     
            **'<select class="form-control" id="datepickerMode" name="datepickerMode" ng-model="component.datepickerMode" ng-options="mode.name as mode.label for mode in modes"></select>'** 
to
   **'<select class="form-control" id="datepickerMode" name="datepickerMode" ng-model="component.datePicker.datepickerMode" ng-options="mode.name as mode.label for mode in modes"></select>'** 

then it work correctly.

sorry
my english is so prool

**Comment by zackurben** [comment]
I'm closing this issue, if you need more help, feel free to open a new issue.
