### ISSUE TITLE
Problem With Add new Component to FormIo 

### ISSUE THREAD

**Issue by j-hashemi** [formio/ngFormBuilder#207]
Hi, I'm using FormIo in my project  and I have problem in adding new component to FormIo source .
I try  the way be approached but I didn't  get any result  !

**Comment by zackurben** [comment]
Hello @j-hashemi, you can find the documentation for adding custom components to the form builder here: https://help.form.io/userguide/#custom

**Comment by j-hashemi** [comment]
Hi , thanks
