### ISSUE TITLE
Required fields not having a red asterisk in the form builder.

### ISSUE THREAD

**Issue by AbdallaMohamed** [formio/ngFormBuilder#226]
With the commit https://github.com/formio/ngFormio/commit/90d015b740642a66af6dfc7a8400c098c34388ca, a change was introduced to how fields are marked as Required. The `isRequired()` function is being used instead of `component.validate.required`. 

The function is being passed to the component in [this line](https://github.com/formio/ngFormio/blob/90d015b740642a66af6dfc7a8400c098c34388ca/src/directives/formioComponent.js#L85)
`$scope.isRequired = $scope.$parent.isRequired;`

That works in the form renderer. However, in the form builder, there's no isRequired function. That prevents required fields from getting the class that renders a red asterisk next to the label.
`ng-class="{\'field-required\': isRequired(component)}" `
That's in the [fieldWrap function here.](https://github.com/formio/ngFormio/blob/master/src/factories/FormioUtils.js#L55)

Any idea how to fix this?

**Comment by travist** [comment]
@randallknutson may need to comment on this one.

**Comment by andreiho** [comment]
@travist @randallknutson Any update on this issue? We'd like to get your opinion first before trying to fix it ourselves.

**Comment by andreiho** [comment]
I fixed this here: https://github.com/formio/ngFormio/pull/318
