### ISSUE TITLE
validationmessage on regex patter

### ISSUE THREAD

**Issue by StefanHoutzager** [formio/ngFormBuilder#249]
Postcode: does not match the pattern ^[1-9][0-9]{3} ?(?!SA|SD|SS)[A-Z]{2}$

this is not understandable for a regular user, it would be nice to be able to edit a custom message

Of course you can use a normal validation for this like
valid = (/^[1-9][0-9]{3} ?(?!SA|SD|SS)[A-Z]{2}$/.test(input)) ? true : 'some message';
so maybe the editable regex pattern is not needed

**Comment by zackurben** [comment]
This is already possible with [custom validation](https://help.form.io/userguide/form-components/#custom-validation); you can do your custom js logic, and if it fails, set `valid` to your error message.

**Comment by StefanHoutzager** [comment]
I mentioned that with the custom validation code. I mean that the editable regex pattern (the input field on the validation tab) is not usable without a custom message.

**Comment by zackurben** [comment]
I see the disconnect, ignore the validation regex input and only use a custom validator like this:

`valid = (/^[1-9][0-9]{3} ?(?!SA|SD|SS)[A-Z]{2}$/.test(input)) ? true : 'some message';`
