### ISSUE TITLE
make pycaffe

### ISSUE THREAD

**Issue by bianlongpeng** [formio/ngFormBuilder#252]
when I configure python2.7 in caffe .there always an error :

 working_set.resolve(self.dist.requires(self.extras),env,installer)))

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve

    raise VersionConflict(dist,req) # XXX put more info here

pkg_resources.VersionConflict: (six 1.5.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.6.0'))

----------------------------------------
Cleaning up...
_**Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/backports.ssl-match-hostname
Storing debug log for failure in /home/bianbian/.pip/pip.log**_
what can I do for it?

**Comment by zackurben** [comment]
@bianlongpeng what is this in context of? This project doesn't use python.

**Comment by bianlongpeng** [comment]
@zackurben I am preparing  Python environment for caffe on ubuntu 14.04 system.I execute commamds as  the following:
sudo apt-get update
sudo apt-get install python-pip python-dev python-numpy
sudo apt-get install gfortran
sudo pip install -r ${CAFFE_ROOT}/python/requirements.txt
when I execute the command"sudo pip install -r ${CAFFE_ROOT}/python/requirements.txt",it indicates an error as shown above. I try many times ,it always indicates this error.The "${CAFFE_ROOT}" is my caffe root directory,I confirm it is right.The "requirements.txt"'s contents are as follows:
Cython>=0.19.2
numpy>=1.7.1
scipy>=0.13.2
scikit-image>=0.9.3
matplotlib>=1.3.1
ipython>=3.0.0
h5py>=2.2.0
leveldb>=0.191
networkx>=1.8.1
nose>=1.3.0
pandas>=0.12.0
python-dateutil>=1.4,<2
protobuf>=2.5.0
python-gflags>=2.0
pyyaml>=3.10
Pillow>=2.3.0
six>=1.1.0
Do you have an method to sove it ?Thank you very much!

**Comment by zackurben** [comment]
This project doesn't use python or caffe.

**Comment by bianlongpeng** [comment]
@zackurben what does this means of  this project doesn't use python or caffe.Sorry ,I can't understand it.Please explain it or tell me how to do ?

**Comment by travist** [comment]
He means the issue you referring to has nothing to do with this project. This project does not use any of the things you are mentioning so your problem is in another project.
