### ISSUE TITLE
DateRange

### ISSUE THREAD

**Issue by prashant93** [formio/ngFormBuilder#262]
How to enable daterange for datetime field?

**Comment by prashant93** [comment]
please close this, I have added custom component for date range.

**Comment by zackurben** [comment]
This is available with the min/max validation settings.

**Comment by prashant93** [comment]
date range like this 
![image](https://cloud.githubusercontent.com/assets/4151470/25473090/a62b777a-2b4b-11e7-962f-de52424c8861.png)

**Comment by vaibhav293** [comment]
@prashant93 did you finish your custom component ?
