### ISSUE TITLE
Need help on Ngformbuilder 

### ISSUE THREAD

**Issue by arajsh03** [formio/ngFormBuilder#283]
Hi All,
 I'm new to form.io. i'm trying to setup the environment in my local(on windows). I've downloaded the code as per the instructions (below url). I don't see the clear instructions like how to complete the setup and run ngformbuilder .

https://github.com/formio/ngFormBuilder/blob/master/README.md

It would be great if some one can provide the detailed steps.

Thanks,
 Raj

**Comment by prashant93** [comment]
download the code and run your index.html.

**Comment by arajsh03** [comment]
Many Thanks for your quick response Prashant.

I've downloaded the code and ran the index.html as you suggested.
But still it is showing the same error message how it was showing before.
Error message: The page can't be displayed 

Running as  'http://localhost:8000/index.htlml' 

tried with different options with folder name in between localhost & index.html,etc..

but none of the options worked.

can you please advise?

thanks,
Raj

**Comment by prashant93** [comment]
I download the project and directly open the index.html using chrome

file:///C:/Users/prashant/Downloads/ngFormBuilder-master/ngFormBuilder-master/index.html#!/

![image](https://cloud.githubusercontent.com/assets/4151470/25694515/a49278ec-30cc-11e7-98c9-fe3a9f6690f5.png)

**Comment by arajsh03** [comment]
Thanks again for your reply Prashant.
yes, i can see the same page when I open it manually, but it is just static page, right?
it should run from application(through localhost), so that we can customize the development on top of it and test it,So I'm trying to run this from localhost. 
Actually my requirement is like ngformbuilder needs to be deployed/integrated with formio.
it would be great if you can provide some steps or instructions source on that lines..

**Comment by travist** [comment]
@arajsh03 the form builder is just a front-end javascript library that generates a JSON schema for the form. To integrate this into a backend platform, you will also need to be running the library https://github.com/formio/formio as a server behind it. I would recommend taking a look at the application called https://github.com/formio/formio-app-formbuilder since it uses this formbuilder connected to the backend API platform to save the forms.

**Comment by arajsh03** [comment]
Thank you travist,
I've runnig formio on my local and also ngformbuilder is ready(downloaded and build the code).
I'm looking for the instructions like how can we integrate both of these ngformbuilder and formio.
can you please provide some source links which refers this integration.

Thanks,
Raj
