### ISSUE TITLE
How do you install the Open Source Version?

### ISSUE THREAD

**Issue by andrewkrowczyk** [formio/ngFormBuilder#32]
There are notes in the help site.  However, I cannot find any instructions on setting this up???

Utilize <form.io> to build your application including your API, documentation, validation and <form.io> which will point to your server for in house hosting. With this option you will need to install:
Docker
Mongo DB

**Comment by travist** [comment]
Hello @andrewkrowczyk.  Thank you for your interest in this module.  We are still working on solidifying our open source offering which will be a runnable project that ties all of the sub-projects (like the form builder) together. We are hoping to have this ready by the end of this month so please stay tuned.

**Comment by karev** [comment]
any news on installing the open source version ?

**Comment by travist** [comment]
That is what I am working on right now. It looks like the release date is going to be closer to the end of September.  Thanks for your patience.

**Comment by travist** [comment]
This is now resolved. You can install open source which includes this repo by going to https//github.com/formio/formio
