### ISSUE TITLE
Field keys get prefixed with 'undefined'

### ISSUE THREAD

**Issue by colons** [formio/ngFormBuilder#412]
It's not true for any of the fields created with form.io itself, and it's not true for the initial fields in [the demo](http://formio.github.io/ngFormBuilder/), but any fields created with the demo (or any fields created with a hosted version of this project) have a `key` property with a prefix of `'undefined'`. For example, the default text field you get when you drag in a text field and hit save, has:

```
{
  "autofocus": false,
  "input": true,
  "tableView": true,
  "inputType": "text",
  "inputMask": "",
  "label": "Text",
  "key": "undefinedText",  // this is not ideal
  "placeholder": "",
  "prefix": "",
  "suffix": "",
  ...
}
```

This leads to some pretty ugly submission JSON. I am not sure where the prefix is coming from.

**Comment by bshivam1** [comment]
Getting the same issue!
