### ISSUE TITLE
Adding new group and adding new component to it

### ISSUE THREAD

**Issue by bshivam1** [formio/ngFormBuilder#422]
I want to create a new group and add my own custom component to it. Can anyone tell how to do it in ngFormBuilder ?

**Comment by bshivam1** [comment]
Done !
module.exports = function(app) {
    app.config([
      'formioComponentsProvider',
      function(formioComponentsProvider) {
        formioComponentsProvider.addGroup('GroupName',{
          title: 'GroupTitle'

        })
        console.log(formioComponentsProvider);
        var isNumeric = function isNumeric(n) {
          return !isNaN(parseFloat(n)) && isFinite(n);
        };
        formioComponentsProvider.register('ComponentName', {
          title: 'ComponentTitle',
//Define template link here
          template: 'formio/components/component.html', 
          settings: {
          
          },
          group: 'GroupName',
          controller: ['$scope', function($scope) {
          
          }]
        });
      }
    ]);

**Comment by virajkanwade** [comment]
Can you please provide more details? Where to write this code? how to call the function?

Thanks

**Comment by Morshed0308** [comment]
Hello @virajkanwade  ,
You can first config your formiocomponents like this
`app.config(['formioComponentsProvider', function (formioComponentsProvider) {`

and then you can add your group and title like below:    

`    formioComponentsProvider.addGroup('Group Name', { title: 'Group Title' });`

after that you can register your custom component using the same group name inside this
```
formioComponentsProvider.register('componentName',{
});
    
```
For example a simple custom component will look like this :

```
app.config(['formioComponentsProvider', function (formioComponentsProvider) {
 
    formioComponentsProvider.addGroup('amazing', { title: 'Custom Template Components' });

formioComponentsProvider.register('reCAPTCHA', {
        title: 'reCAPTCHA',
        template: 'The URL where the component will load',
        controller: ['$scope', function ($scope) {
        
        }],
        group: 'amazing',
        icon: 'fa fa-refresh',  
      ////Here you can add your own json scema for this component///////////

    });

}]);
```
Hope this helps.
