### ISSUE TITLE
panel/fieldset collapsible and collapsed

### ISSUE THREAD

**Issue by olivbd** [formio/ngFormBuilder#429]
The options "collapsible" and "collapsed" don't work.

I checked the case "collapsible" in the Display tab of the properties component. 
In the rendered form, when I click on the panel title (or on the fieldset title), there is no effect.

The case "collapsed" don't collapse the panel/fieldset component by default.

**Comment by sunil-lulla** [comment]
Hi @olivbd 
Did you get any solution to this, I am stuck with the same thing?

**Comment by travist** [comment]
This option is really only implemented within the "core" renderer @ https://github.com/formio/formio.js. I do not believe we will backport that feature into the Angular 1.x library since we are using the core renderer moving forward.

**Comment by olivbd** [comment]
Some people like me don't use the "core" renderer, and use only ngFormio+ngFormBuilder for their projets. I forked this projet to implements this missing feature (and other specific things), but I can make a pull request
