### ISSUE TITLE
How to create custom component with draggable property inside it.

### ISSUE THREAD

**Issue by Morshed0308** [formio/ngFormBuilder#440]
I am creating a custom component like '**Data Grid'** of special components. I am stuck at creating the drag able component inside Data Grid component. How can I create custom component with draggable component inside it.
I have already registered the component using  **formioComponentsProvider.register({})**
 and added the template in **app.run().** 
what I want is a draggable layout like datagrid component has inside it. How can I create that?
@travist @lukeggchapman @screamy @zackurben

**Comment by randallknutson** [comment]
Your best bet is to look at examples of how we do that. You need to add a dropzone with Dragula. The best way to find this is to look at the WebformBuilder.js, EditGrid.js and Datagrid.js and see how they are done. If you extend the NestedComponent it will automatically add this.
