### ISSUE TITLE
How to turn off searching option in select component?

### ISSUE THREAD

**Issue by Morshed0308** [formio/ngFormBuilder#444]
In the select dropdown options , I don't want to enable the filtering option with typing. Infact I don't want the searching option in the select dropdown. How can I stop this?  Thanks in Advance.
@travist @lukeggchapman

**Comment by jhen1422** [comment]
@Morshed0308 
Hello,

You can disable the searching option for the Select dropdown using our 3x builder which can be found at https://beta.form.io/. Simply uncheck the 'Enable Static Search' on Beta. This setting will then translate back to ngFormBuilder once configured.

**Comment by Morshed0308** [comment]
How Can I do this with 2.x builder. I want select component to behave like normal select component.

**Comment by randallknutson** [comment]
Unfortunately this isn't a supported feature in the 2.x form builder. We are not adding new features to 2.x any longer but if you wanted to do it and add a pull request we would consider pulling it in.
